"""
UHF Hydrodynamic Electromagnetism v1 — Emergent Coulomb Law from GP Vortices
=============================================================================
Tests whether topological phase singularities in a 2D Gross-Pitaevskii
superfluid vacuum reproduce the classical electrostatic force law.

In 2D, point vortices interact via the superflow velocity field:
  v_induced = κ/(2πr)    (the 2D Coulomb analog of E ∝ 1/r)

This is the hydrodynamic equivalent of Coulomb's law: the "force" on a
topological defect is the velocity field generated by other defects.

Two scenarios:
  1. Like-charge: two +1 vortices (co-rotate, repel)
  2. Opposite-charge: +1 and -1 vortices (translate as dipole, attract)

Method: Measure instantaneous defect velocity at multiple separations.
Fit v(r) to A/r^β. Target: β ≈ 1.0.

Solver: Split-step Fourier spectral method (2D).
Grid: 256×256, L = 60ξ, ξ = 1.
"""

import os, sys, time, json
import numpy as np
from scipy.ndimage import uniform_filter1d

try:
    import cupy as cp
    from cupyx.scipy.fft import fft2, ifft2
    GPU_AVAILABLE = True
except ImportError:
    print("NOTE: CuPy not available, using NumPy.")
    import numpy as cp
    from scipy.fft import fft2, ifft2
    GPU_AVAILABLE = False

# ==================================================================
# 1. NATURAL UNITS & GRID
# ==================================================================
HBAR  = 1.0
M     = 1.0
G_INT = 1.0
RHO0  = 1.0
MU    = G_INT * RHO0
CS    = 1.0
XI    = 1.0 / np.sqrt(2.0)

NX, NY = 256, 256
L      = 60.0 * XI          # large box to minimize image effects
DX     = L / NX
DT_IMAG = 0.01              # conservative imaginary-time step
DT_REAL = 0.005              # small real-time step for accuracy

N_RELAX      = 800           # thorough relaxation with pinning
KAPPA        = 2.0 * np.pi   # quantum of circulation (natural units)

# Pin vortices strongly during relaxation
PIN_AMP   = 5.0              # strong pinning
PIN_WIDTH = 1.5 * XI

# Separations to test (in units of ξ)
R0_LIST = [5.0, 7.0, 9.0, 11.0, 13.0, 15.0, 18.0, 21.0, 25.0]

# Velocity measurement: evolve briefly after releasing pins, track core motion
N_MEASURE    = 200           # steps for velocity measurement
MEASURE_DT   = DT_REAL
TRACK_EVERY  = 10            # track every 10 steps

print("=" * 65)
print("  UHF Hydrodynamic Electromagnetism v1")
print("=" * 65)
print(f"  Grid: {NX}x{NY}, L={L/XI:.0f}ξ, dx={DX/XI:.3f}ξ")
print(f"  Relax: {N_RELAX} steps (dt={DT_IMAG}), pin_amp={PIN_AMP}")
print(f"  Measure: {N_MEASURE} steps (dt={DT_REAL})")
print(f"  Separations: {R0_LIST} ξ")
print(f"  κ = {KAPPA:.4f}")
print("=" * 65)


# ==================================================================
# 2. BUILD K-SPACE GRID (2D)
# ==================================================================
def build_k2_grid():
    kx = 2.0 * np.pi * np.fft.fftfreq(NX, d=DX)
    ky = 2.0 * np.pi * np.fft.fftfreq(NY, d=DX)
    KX, KY = np.meshgrid(kx, ky, indexing='ij')
    k2 = KX**2 + KY**2
    return cp.asarray(k2, dtype=cp.float64)


# ==================================================================
# 3. COORDINATES
# ==================================================================
def make_coords():
    x = np.linspace(-L/2, L/2, NX, endpoint=False) + DX/2
    y = np.linspace(-L/2, L/2, NY, endpoint=False) + DX/2
    X, Y = np.meshgrid(x, y, indexing='ij')
    return X, Y


# ==================================================================
# 4. VORTEX INITIALIZATION
# ==================================================================
def init_vortex_pair(X, Y, x1, y1, q1, x2, y2, q2):
    """Initialize a pair of point vortices with charges q1, q2."""
    theta1 = q1 * np.arctan2(Y - y1, X - x1)
    theta2 = q2 * np.arctan2(Y - y2, X - x2)
    r1 = np.sqrt((X - x1)**2 + (Y - y1)**2)
    r2 = np.sqrt((X - x2)**2 + (Y - y2)**2)
    rho = RHO0 * np.tanh(r1 / XI)**2 * np.tanh(r2 / XI)**2
    psi = np.sqrt(rho) * np.exp(1j * (theta1 + theta2))
    return cp.asarray(psi, dtype=cp.complex128)


def make_pin_potential(X, Y, x1, y1, x2, y2):
    """Strong Gaussian pinning at both core locations."""
    r1_sq = (X - x1)**2 + (Y - y1)**2
    r2_sq = (X - x2)**2 + (Y - y2)**2
    V = PIN_AMP * (np.exp(-r1_sq / (2 * PIN_WIDTH**2)) +
                   np.exp(-r2_sq / (2 * PIN_WIDTH**2)))
    return cp.asarray(V, dtype=cp.float64)


# ==================================================================
# 5. SPLIT-STEP FOURIER EVOLUTION
# ==================================================================
def split_step(psi, k2, dt, n_steps, imaginary=False, pin_potential=None):
    """Split-step Fourier propagation (imaginary or real time)."""
    for step in range(n_steps):
        rho = cp.abs(psi)**2
        V_nl = G_INT * rho - MU
        if pin_potential is not None:
            V_nl = V_nl + pin_potential

        if imaginary:
            psi *= cp.exp(-dt * 0.5 * V_nl)
        else:
            psi *= cp.exp(-1j * dt * 0.5 * V_nl)

        psi_k = fft2(psi)
        if imaginary:
            psi_k *= cp.exp(-dt * 0.5 * k2 / M)
        else:
            psi_k *= cp.exp(-1j * dt * 0.5 * k2 / M)
        psi = ifft2(psi_k)

        rho = cp.abs(psi)**2
        V_nl = G_INT * rho - MU
        if pin_potential is not None:
            V_nl = V_nl + pin_potential

        if imaginary:
            psi *= cp.exp(-dt * 0.5 * V_nl)
        else:
            psi *= cp.exp(-1j * dt * 0.5 * V_nl)

        if imaginary:
            norm = cp.sqrt(cp.sum(cp.abs(psi)**2) * DX**2)
            psi *= cp.sqrt(RHO0 * L**2) / norm

    return psi


# ==================================================================
# 6. VORTEX CORE TRACKING (PHASE WINDING)
# ==================================================================
def find_vortex_core(psi_np, x_prev, y_prev, X, Y, window=5.0):
    """Locate vortex core via density minimum in a window."""
    w = window * XI
    mask = ((X - x_prev)**2 + (Y - y_prev)**2) < w**2
    rho = np.abs(psi_np)**2
    rho_masked = np.where(mask, rho, 1e10)
    idx = np.unravel_index(np.argmin(rho_masked), rho_masked.shape)
    return X[idx], Y[idx]


def measure_core_velocity(psi, k2, X, Y, x1_0, y1_0, x2_0, y2_0):
    """
    Release pinning, evolve briefly, track cores to get velocity.
    Returns: (v1x, v1y, v2x, v2y, positions over time)
    """
    x1, y1 = x1_0, y1_0
    x2, y2 = x2_0, y2_0

    times = []
    x1_hist, y1_hist = [], []
    x2_hist, y2_hist = [], []

    for step in range(N_MEASURE):
        # Real-time step (NO pinning)
        rho = cp.abs(psi)**2
        V_nl = G_INT * rho - MU
        psi *= cp.exp(-1j * MEASURE_DT * 0.5 * V_nl)
        psi_k = fft2(psi)
        psi_k *= cp.exp(-1j * MEASURE_DT * 0.5 * k2 / M)
        psi = ifft2(psi_k)
        rho = cp.abs(psi)**2
        V_nl = G_INT * rho - MU
        psi *= cp.exp(-1j * MEASURE_DT * 0.5 * V_nl)

        if step % TRACK_EVERY == 0:
            psi_np = cp.asnumpy(psi) if GPU_AVAILABLE else np.array(psi)
            x1, y1 = find_vortex_core(psi_np, x1, y1, X, Y)
            x2, y2 = find_vortex_core(psi_np, x2, y2, X, Y)
            t = step * MEASURE_DT
            times.append(t)
            x1_hist.append(x1)
            y1_hist.append(y1)
            x2_hist.append(x2)
            y2_hist.append(y2)

    times = np.array(times)
    x1h = np.array(x1_hist)
    y1h = np.array(y1_hist)
    x2h = np.array(x2_hist)
    y2h = np.array(y2_hist)

    # Compute velocities via first differences (much cleaner than 2nd derivative)
    dt_arr = np.diff(times)

    # Velocity of each core
    v1x = np.diff(x1h) / dt_arr
    v1y = np.diff(y1h) / dt_arr
    v2x = np.diff(x2h) / dt_arr
    v2y = np.diff(y2h) / dt_arr

    # Separation over time
    r_arr = np.sqrt((x2h - x1h)**2 + (y2h - y1h)**2)

    return {
        'times': times,
        'x1': x1h, 'y1': y1h, 'x2': x2h, 'y2': y2h,
        'v1x': v1x, 'v1y': v1y, 'v2x': v2x, 'v2y': v2y,
        'r': r_arr,
        'v1_mag': np.sqrt(v1x**2 + v1y**2),
        'v2_mag': np.sqrt(v2x**2 + v2y**2)
    }


# ==================================================================
# 7. POWER-LAW FIT
# ==================================================================
def fit_power_law(r, v):
    """Fit |v| = A / r^β via log-linear regression."""
    mask = (v > 1e-12) & (r > 2.0 * XI) & np.isfinite(v) & np.isfinite(r)
    r_f = r[mask]
    v_f = v[mask]
    if len(r_f) < 4:
        return 0.0, 0.0, 0.0

    log_r = np.log(r_f)
    log_v = np.log(v_f)
    coeffs = np.polyfit(log_r, log_v, 1)
    beta = -coeffs[0]
    A = np.exp(coeffs[1])

    log_v_pred = coeffs[0] * log_r + coeffs[1]
    ss_res = np.sum((log_v - log_v_pred)**2)
    ss_tot = np.sum((log_v - np.mean(log_v))**2)
    R2 = 1.0 - ss_res / ss_tot if ss_tot > 0 else 0.0

    return A, beta, R2


# ==================================================================
# 8. MAIN
# ==================================================================
def run_scenario(scenario_name, q1, q2):
    """Run all separations for a given charge configuration."""
    print(f"\n{'='*65}")
    print(f"  SCENARIO: {scenario_name} (q1={q1:+d}, q2={q2:+d})")
    print(f"{'='*65}")

    X, Y = make_coords()
    k2 = build_k2_grid()

    # Collect (r, v) data across all separations
    all_r = []
    all_v = []
    per_sep_results = []

    for r0_xi in R0_LIST:
        r0 = r0_xi * XI
        x1_0 = -r0 / 2.0
        x2_0 = +r0 / 2.0
        y1_0 = 0.0
        y2_0 = 0.0

        print(f"\n  r₀ = {r0_xi:.0f}ξ ({r0:.3f})")

        # Initialize & relax with strong pinning
        psi = init_vortex_pair(X, Y, x1_0, y1_0, q1, x2_0, y2_0, q2)
        pin_pot = make_pin_potential(X, Y, x1_0, y1_0, x2_0, y2_0)

        print(f"    Relaxing ({N_RELAX} steps, pinned)...", end=" ", flush=True)
        psi = split_step(psi, k2, DT_IMAG, N_RELAX, imaginary=True,
                         pin_potential=pin_pot)
        print("done.")

        # Verify cores survived
        psi_np = cp.asnumpy(psi) if GPU_AVAILABLE else np.array(psi)
        x1_v, y1_v = find_vortex_core(psi_np, x1_0, y1_0, X, Y, window=3.0)
        x2_v, y2_v = find_vortex_core(psi_np, x2_0, y2_0, X, Y, window=3.0)
        r_post = np.sqrt((x2_v - x1_v)**2 + (y2_v - y1_v)**2)

        # Check density at core
        rho_field = np.abs(psi_np)**2
        i1 = np.unravel_index(np.argmin(np.where(
            ((X-x1_v)**2+(Y-y1_v)**2) < (2*XI)**2, rho_field, 1e10)),
            rho_field.shape)
        rho_core1 = rho_field[i1]

        print(f"    Cores: ({x1_v/XI:.1f},{y1_v/XI:.1f})ξ & "
              f"({x2_v/XI:.1f},{y2_v/XI:.1f})ξ, "
              f"sep={r_post/XI:.1f}ξ, ρ_core={rho_core1:.4f}")

        if rho_core1 > 0.5:
            print(f"    WARNING: Core density too high ({rho_core1:.3f}), "
                  f"vortex may have annihilated. Skipping.")
            per_sep_results.append({
                'r0_xi': r0_xi, 'status': 'annihilated'
            })
            continue

        # Measure velocity (release pins)
        print(f"    Measuring velocity ({N_MEASURE} steps)...", end=" ", flush=True)
        t0 = time.time()
        data = measure_core_velocity(psi, k2, X, Y, x1_v, y1_v, x2_v, y2_v)
        elapsed = time.time() - t0
        print(f"done ({elapsed:.1f}s).")

        # Use early-time velocities (before significant motion changes r)
        n_early = min(5, len(data['v1_mag']))
        v1_early = np.mean(data['v1_mag'][:n_early])
        v2_early = np.mean(data['v2_mag'][:n_early])
        v_avg = (v1_early + v2_early) / 2.0
        r_meas = np.mean(data['r'][:n_early+1])

        # Theoretical prediction: v = κ/(2πr) for each vortex
        v_theory = KAPPA / (2.0 * np.pi * r_meas)

        print(f"    v_measured = {v_avg:.6f}, v_theory(κ/2πr) = {v_theory:.6f}, "
              f"ratio = {v_avg/v_theory:.3f}")

        all_r.append(r_meas)
        all_v.append(v_avg)
        per_sep_results.append({
            'r0_xi': r0_xi,
            'r_meas': float(r_meas),
            'v_measured': float(v_avg),
            'v_theory': float(v_theory),
            'ratio': float(v_avg / v_theory) if v_theory > 0 else 0.0,
            'status': 'ok'
        })

        # Also add all time-resolved data points
        for i in range(len(data['v1_mag'])):
            r_i = data['r'][i]
            v_i = (data['v1_mag'][i] + data['v2_mag'][i]) / 2.0
            if r_i > 3.0 * XI and v_i > 1e-12:
                all_r.append(r_i)
                all_v.append(v_i)

    # Global fit across all (r, v) data
    all_r = np.array(all_r)
    all_v = np.array(all_v)

    if len(all_r) > 4:
        A, beta, R2 = fit_power_law(all_r, all_v)
    else:
        A, beta, R2 = 0, 0, 0

    return per_sep_results, A, beta, R2, all_r, all_v


def print_summary(like_res, like_fit, opp_res, opp_fit):
    """Print summary table and conclusion."""
    like_per, like_A, like_beta, like_R2, _, _ = like_fit
    opp_per, opp_A, opp_beta, opp_R2, _, _ = opp_fit

    print("\n" + "=" * 80)
    print("  RESULTS TABLE: Hydrodynamic Electromagnetism v1")
    print("=" * 80)

    header = (f"  {'Scenario':<28} {'r₀/ξ':>5} {'r_meas/ξ':>9} "
              f"{'v_meas':>10} {'v_theory':>10} {'ratio':>7}")
    print(header)
    print("  " + "-" * 76)

    for res in like_per:
        if res.get('status') == 'annihilated':
            print(f"  {'Like (+1,+1)':<28} {res['r0_xi']:>5.0f} "
                  f"{'ANNIHILATED':>9}")
            continue
        print(f"  {'Like (+1,+1)':<28} {res['r0_xi']:>5.0f} "
              f"{res['r_meas']/XI:>9.1f} "
              f"{res['v_measured']:>10.6f} {res['v_theory']:>10.6f} "
              f"{res['ratio']:>7.3f}")

    for res in opp_per:
        if res.get('status') == 'annihilated':
            print(f"  {'Opposite (+1,-1)':<28} {res['r0_xi']:>5.0f} "
                  f"{'ANNIHILATED':>9}")
            continue
        print(f"  {'Opposite (+1,-1)':<28} {res['r0_xi']:>5.0f} "
              f"{res['r_meas']/XI:>9.1f} "
              f"{res['v_measured']:>10.6f} {res['v_theory']:>10.6f} "
              f"{res['ratio']:>7.3f}")

    print("  " + "-" * 76)
    print(f"\n  Like-charge global fit:     v = {like_A:.4f}/r^{like_beta:.3f}, "
          f"R² = {like_R2:.4f}")
    print(f"  Opposite-charge global fit: v = {opp_A:.4f}/r^{opp_beta:.3f}, "
          f"R² = {opp_R2:.4f}")

    mean_beta = (like_beta + opp_beta) / 2.0

    if abs(mean_beta - 1.0) < 0.15 and min(like_R2, opp_R2) > 0.7:
        print(f"\n  CONCLUSION: Emergent velocity scales as 1/r "
              f"(β ≈ {mean_beta:.2f})")
        print(f"  → Hydrodynamic Coulomb law CONFIRMED in 2D GP vacuum.")
    elif abs(mean_beta - 1.0) < 0.25:
        print(f"\n  CONCLUSION: β ≈ {mean_beta:.2f} — consistent with 1/r "
              f"within finite-box corrections.")
    else:
        print(f"\n  CONCLUSION: β = {mean_beta:.2f} — requires further "
              f"investigation.")

    print("=" * 80)
    return mean_beta


if __name__ == "__main__":
    print(f"\nGPU: {'CuPy (' + str(cp.cuda.runtime.getDeviceCount()) + ' devices)' if GPU_AVAILABLE else 'NumPy fallback'}")

    # Scenario 1: Like-charge repulsion
    like_per, like_A, like_beta, like_R2, like_r, like_v = \
        run_scenario("Like-Charge Repulsion", q1=+1, q2=+1)

    # Scenario 2: Opposite-charge attraction
    opp_per, opp_A, opp_beta, opp_R2, opp_r, opp_v = \
        run_scenario("Opposite-Charge Attraction", q1=+1, q2=-1)

    # Summary
    like_fit = (like_per, like_A, like_beta, like_R2, like_r, like_v)
    opp_fit = (opp_per, opp_A, opp_beta, opp_R2, opp_r, opp_v)
    mean_beta = print_summary(like_per, like_fit, opp_per, opp_fit)

    # Save results
    out_path = os.path.join(os.path.dirname(__file__), "coulomb_v1_results.json")
    save_data = {
        'like_charge': [r for r in like_per],
        'opposite_charge': [r for r in opp_per],
        'like_fit': {'A': like_A, 'beta': like_beta, 'R2': like_R2},
        'opp_fit': {'A': opp_A, 'beta': opp_beta, 'R2': opp_R2},
        'mean_beta': float(mean_beta)
    }
    with open(out_path, 'w') as f:
        json.dump(save_data, f, indent=2, default=str)
    print(f"\n  Results saved to {out_path}")
